exclude:
  - _assets/
  - assets/lib/*.txt
  - assets/lib/lato/src/
  - bin/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - README.md
  - scripts/
  - _lessons/test/
  - _resources/test/
  - _subclubs/test/
  - _lessons/web-development/
  - _resources/web-development/
  - _subclubs/web-development/
  - Vagrantfile
  - vagrant-ssh.config
  - 404.html # Excluded as Github pages won't build it anyways

production: true
